name: "kv_sandbox"


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kv_sandbox:
    staging:
      +materialized: view
    marts:
      +materialized: table
flags:
  require_generic_test_arguments_property: true