sources:
  - name: tpch_now.lineitem
    schema: raw

  - name: tpch_now.orders
    schema: raw

  - name: tpch_sf001.partsupp
    schema: raw

  - name: tpch_sf001.part
    schema: raw

  - name: tpch_sf001.supplier
    schema: raw